In [96]:
import pandas as pd

In [97]:
con = pd.read_csv('../../data/경기도/원본/용도지역별 결제업종 분석.csv')

In [98]:
## 2019년10월 ~ 2020년6월
con

,분석인덱스,법정동코드,우편번호,용도지역명,주용도명,가맹점업종명,지역별업종수,일반결제금액,정책결제금액
0,0,4182025021,12413,일반상업지역,제1종근린생활시설,건강식품,1352,280000,40000
1,1,4182025021,12413,일반상업지역,제1종근린생활시설,건축자재,676,30000,75800
2,2,4182025021,12413,일반상업지역,제1종근린생활시설,기타,676,20000,108400
3,3,4182025021,12413,일반상업지역,제1종근린생활시설,기타의료기관,338,69030,19210
4,4,4182025021,12413,일반상업지역,제1종근린생활시설,레저업소,1700,937200,3007600
...,...,...,...,...,...,...,...,...,...
1790420,1790420,4145012300,12986,도시지역,교육연구시설,전기제품,2429,0,6600
1790421,1790421,4145012300,12986,도시지역,교육연구시설,주방용구,2602,0,0
1790422,1790422,4145012300,12986,도시지역,교육연구시설,직물,1502,0,1000100
1790423,1790423,4145012300,12986,도시지역,교육연구시설,학원,996,90000,202500
1790424,1790424,4145012300,12986,도시지역,교육연구시설,회원제형태,2028,1428000,6029000

In [99]:
## 분석인덱스 열 제거
con.drop(columns='분석인덱스',inplace=True)
con

,법정동코드,우편번호,용도지역명,주용도명,가맹점업종명,지역별업종수,일반결제금액,정책결제금액
0,4182025021,12413,일반상업지역,제1종근린생활시설,건강식품,1352,280000,40000
1,4182025021,12413,일반상업지역,제1종근린생활시설,건축자재,676,30000,75800
2,4182025021,12413,일반상업지역,제1종근린생활시설,기타,676,20000,108400
3,4182025021,12413,일반상업지역,제1종근린생활시설,기타의료기관,338,69030,19210
4,4182025021,12413,일반상업지역,제1종근린생활시설,레저업소,1700,937200,3007600
...,...,...,...,...,...,...,...,...
1790420,4145012300,12986,도시지역,교육연구시설,전기제품,2429,0,6600
1790421,4145012300,12986,도시지역,교육연구시설,주방용구,2602,0,0
1790422,4145012300,12986,도시지역,교육연구시설,직물,1502,0,1000100
1790423,4145012300,12986,도시지역,교육연구시설,학원,996,90000,202500
1790424,4145012300,12986,도시지역,교육연구시설,회원제형태,2028,1428000,6029000

In [100]:
## 법정동코드 시군코드만 남기기
con['법정동코드'] = con['법정동코드'].astype(str).str[:5]
con

         법정동코드   우편번호   용도지역명       주용도명  가맹점업종명  지역별업종수   일반결제금액   정책결제금액
0        41820  12413  일반상업지역  제1종근린생활시설    건강식품    1352   280000    40000
1        41820  12413  일반상업지역  제1종근린생활시설    건축자재     676    30000    75800
2        41820  12413  일반상업지역  제1종근린생활시설      기타     676    20000   108400
3        41820  12413  일반상업지역  제1종근린생활시설  기타의료기관     338    69030    19210
4        41820  12413  일반상업지역  제1종근린생활시설    레저업소    1700   937200  3007600
...        ...    ...     ...        ...     ...     ...      ...      ...
1790420  41450  12986    도시지역     교육연구시설    전기제품    2429        0     6600
1790421  41450  12986    도시지역     교육연구시설    주방용구    2602        0        0
1790422  41450  12986    도시지역     교육연구시설      직물    1502        0  1000100
1790423  41450  12986    도시지역     교육연구시설      학원     996    90000   202500
1790424  41450  12986    도시지역     교육연구시설   회원제형태    2028  1428000  6029000

[1790425 rows x 8 columns]

In [101]:
# 법정동코드 정수형으로 변환
con['법정동코드'] = con['법정동코드'].astype(int)
con.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1790425 entries, 0 to 1790424
Data columns (total 8 columns):
 #   Column  Dtype
---  ------  -----
 0   법정동코드   int32
 1   우편번호    int64
 2   용도지역명   object
 3   주용도명    object
 4   가맹점업종명  object
 5   지역별업종수  int64
 6   일반결제금액  int64
 7   정책결제금액  int64
dtypes: int32(1), int64(4), object(3)
memory usage: 102.4+ MB

In [102]:
## 시군 코드, 시군명
a = [41610, 41630, 41650, 41670, 41800, 41820, 41830, 41110, 41130,
       41150, 41170, 41190, 41210, 41220, 41250, 41270, 41280, 41290,
       41310, 41360, 41370, 41390, 41550, 41570, 41590, 41410, 41430,
       41450, 41460, 41480, 41500]
b = ['광주시','양주시','포천시','여주시','연천군','가평군','양평군','수원시','성남시','의정부시','안양시','부천시','광명시',
'평택시','동두천시','안산시','고양시','과천시','구리시','남양주시','오산시','시흥시','안성시','김포시','화성시','군포시','의왕시',
'하남시','용인시','파주시','이천시']

In [103]:
## 시군 코드를 시군명으로 변경
for code, name in zip(a, b):
    con['법정동코드'] = con['법정동코드'].replace(code, name)
    print(f"'{code}'코드 '{name}'로 변경완료")

'41610'코드 '광주시'로 변경완료
'41630'코드 '양주시'로 변경완료
'41650'코드 '포천시'로 변경완료
'41670'코드 '여주시'로 변경완료
'41800'코드 '연천군'로 변경완료
'41820'코드 '가평군'로 변경완료
'41830'코드 '양평군'로 변경완료
'41110'코드 '수원시'로 변경완료
'41130'코드 '성남시'로 변경완료
'41150'코드 '의정부시'로 변경완료
'41170'코드 '안양시'로 변경완료
'41190'코드 '부천시'로 변경완료
'41210'코드 '광명시'로 변경완료
'41220'코드 '평택시'로 변경완료
'41250'코드 '동두천시'로 변경완료
'41270'코드 '안산시'로 변경완료
'41280'코드 '고양시'로 변경완료
'41290'코드 '과천시'로 변경완료
'41310'코드 '구리시'로 변경완료
'41360'코드 '남양주시'로 변경완료
'41370'코드 '오산시'로 변경완료
'41390'코드 '시흥시'로 변경완료
'41550'코드 '안성시'로 변경완료
'41570'코드 '김포시'로 변경완료
'41590'코드 '화성시'로 변경완료
'41410'코드 '군포시'로 변경완료
'41430'코드 '의왕시'로 변경완료
'41450'코드 '하남시'로 변경완료
'41460'코드 '용인시'로 변경완료
'41480'코드 '파주시'로 변경완료
'41500'코드 '이천시'로 변경완료

In [104]:
con.columns

Index(['법정동코드', '우편번호', '용도지역명', '주용도명', '가맹점업종명', '지역별업종수', '일반결제금액',
       '정책결제금액'],
      dtype='object')

In [105]:
## 변경 제대로 되었는 지 확인
con['법정동코드'].nunique()

40

In [106]:
con['법정동코드'].unique()

array(['가평군', 41281, 41287, '과천시', '광명시', '광주시', '구리시', '군포시', '김포시',
       '남양주시', '동두천시', '부천시', 41135, 41133, 41131, 41113, 41115, 41117,
       41463, 41111, '시흥시', 41273, 41271, '안성시', 41173, 41171, '양주시',
       '양평군', '여주시', '연천군', '오산시', 41465, 41461, '의왕시', '의정부시', '이천시',
       '파주시', '평택시', '포천시', '하남시'], dtype=object)

In [107]:
def change(x):
    if type(x) == int:
        x /= 10
        x = int(x)
        x *= 10
    return x

In [108]:
## 시군코드 제대로 바뀌지 않은 것 변경
test1 =  con['법정동코드'].map(
    change
)

In [113]:
test1.nunique()

30

In [112]:
test1.unique()

array(['가평군', 41280, '과천시', '광명시', '광주시', '구리시', '군포시', '김포시', '남양주시',
       '동두천시', '부천시', 41130, 41110, 41460, '시흥시', 41270, '안성시', 41170,
       '양주시', '양평군', '여주시', '연천군', '오산시', '의왕시', '의정부시', '이천시', '파주시',
       '평택시', '포천시', '하남시'], dtype=object)

In [114]:
con['법정동코드'] = test1

In [123]:
con['법정동코드'].unique()

array(['가평군', 41280, '과천시', '광명시', '광주시', '구리시', '군포시', '김포시', '남양주시',
       '동두천시', '부천시', 41130, 41110, 41460, '시흥시', 41270, '안성시', 41170,
       '양주시', '양평군', '여주시', '연천군', '오산시', '의왕시', '의정부시', '이천시', '파주시',
       '평택시', '포천시', '하남시'], dtype=object)

In [115]:
## 시군 코드, 시군명
a = [41610, 41630, 41650, 41670, 41800, 41820, 41830, 41110, 41130,
       41150, 41170, 41190, 41210, 41220, 41250, 41270, 41280, 41290,
       41310, 41360, 41370, 41390, 41550, 41570, 41590, 41410, 41430,
       41450, 41460, 41480, 41500]
b = ['광주시','양주시','포천시','여주시','연천군','가평군','양평군','수원시','성남시','의정부시','안양시','부천시','광명시',
'평택시','동두천시','안산시','고양시','과천시','구리시','남양주시','오산시','시흥시','안성시','김포시','화성시','군포시','의왕시',
'하남시','용인시','파주시','이천시']

In [124]:
## 다시 시군 코드를 시군명으로 변경
for code, name in zip(a, b):
    test1 = test1.replace(code, name)
    print(f"'{code}'코드 '{name}'로 변경완료")

'41610'코드 '광주시'로 변경완료
'41630'코드 '양주시'로 변경완료
'41650'코드 '포천시'로 변경완료
'41670'코드 '여주시'로 변경완료
'41800'코드 '연천군'로 변경완료
'41820'코드 '가평군'로 변경완료
'41830'코드 '양평군'로 변경완료
'41110'코드 '수원시'로 변경완료
'41130'코드 '성남시'로 변경완료
'41150'코드 '의정부시'로 변경완료
'41170'코드 '안양시'로 변경완료
'41190'코드 '부천시'로 변경완료
'41210'코드 '광명시'로 변경완료
'41220'코드 '평택시'로 변경완료
'41250'코드 '동두천시'로 변경완료
'41270'코드 '안산시'로 변경완료
'41280'코드 '고양시'로 변경완료
'41290'코드 '과천시'로 변경완료
'41310'코드 '구리시'로 변경완료
'41360'코드 '남양주시'로 변경완료
'41370'코드 '오산시'로 변경완료
'41390'코드 '시흥시'로 변경완료
'41550'코드 '안성시'로 변경완료
'41570'코드 '김포시'로 변경완료
'41590'코드 '화성시'로 변경완료
'41410'코드 '군포시'로 변경완료
'41430'코드 '의왕시'로 변경완료
'41450'코드 '하남시'로 변경완료
'41460'코드 '용인시'로 변경완료
'41480'코드 '파주시'로 변경완료
'41500'코드 '이천시'로 변경완료

In [127]:
test1.unique()

array(['가평군', '고양시', '과천시', '광명시', '광주시', '구리시', '군포시', '김포시', '남양주시',
       '동두천시', '부천시', '성남시', '수원시', '용인시', '시흥시', '안산시', '안성시', '안양시',
       '양주시', '양평군', '여주시', '연천군', '오산시', '의왕시', '의정부시', '이천시', '파주시',
       '평택시', '포천시', '하남시'], dtype=object)

In [128]:
con['법정동코드'] = test1

In [129]:
## 41590 화성시가 없다.
# 원본 데이터 확인한 결과 화성시 데이터 없는 게 맞다.
con['법정동코드'].unique()

array(['가평군', '고양시', '과천시', '광명시', '광주시', '구리시', '군포시', '김포시', '남양주시',
       '동두천시', '부천시', '성남시', '수원시', '용인시', '시흥시', '안산시', '안성시', '안양시',
       '양주시', '양평군', '여주시', '연천군', '오산시', '의왕시', '의정부시', '이천시', '파주시',
       '평택시', '포천시', '하남시'], dtype=object)

In [133]:
## 우편번호 컬럼 지우기 
con.drop(columns='우편번호', inplace=True)
con

        법정동코드   용도지역명       주용도명  가맹점업종명  지역별업종수   일반결제금액   정책결제금액
0         가평군  일반상업지역  제1종근린생활시설    건강식품    1352   280000    40000
1         가평군  일반상업지역  제1종근린생활시설    건축자재     676    30000    75800
2         가평군  일반상업지역  제1종근린생활시설      기타     676    20000   108400
3         가평군  일반상업지역  제1종근린생활시설  기타의료기관     338    69030    19210
4         가평군  일반상업지역  제1종근린생활시설    레저업소    1700   937200  3007600
...       ...     ...        ...     ...     ...      ...      ...
1790420   하남시    도시지역     교육연구시설    전기제품    2429        0     6600
1790421   하남시    도시지역     교육연구시설    주방용구    2602        0        0
1790422   하남시    도시지역     교육연구시설      직물    1502        0  1000100
1790423   하남시    도시지역     교육연구시설      학원     996    90000   202500
1790424   하남시    도시지역     교육연구시설   회원제형태    2028  1428000  6029000

[1790425 rows x 7 columns]

In [134]:
con.to_csv('../../data/경기도/전처리 후/용도지역별 결제업종 분석전처리.csv',index=False)

In [ ]:
## 유통업 영리 : 편의점, 대형할인점, 홈쇼핑, 백화점 등