In [1]:
import pandas as pd

In [2]:
grdp = pd.read_excel('../../../data/경기도/원본/등급기준/경기도grdp.xlsx')

In [6]:
grdp = grdp.rename(columns={'Unnamed: 0':'시군구명'})
grdp

    시군구명  2017년  2018년  2019년  2020년  2021년
0    수원시   2854   2971   3080   2796   3031
1    성남시   4271   4455   4704   5030   5432
2    의정부   1598   1678   1686   1625   1614
3    안양시   2941   3144   3345   3221   3388
4    부천시   2013   2082   2119   2191   2227
5    광명시   2274   2485   2435   2615   2754
6    평택시   6573   7010   6433   6091   6424
7   동두천시   1973   1870   1946   1922   1939
8    안산시   3898   3941   3969   3799   3964
9    고양시   1953   2086   2077   2048   2114
10   과천시   7871   8409   8340   7243   6885
11   구리시   1793   1864   1805   1758   1871
12  남양주시   1541   1641   1678   1805   1822
13   오산시   2578   2622   2578   2463   2636
14   시흥시   3912   3766   3540   3465   3537
15   군포시   2583   2703   2747   2659   2721
16   의왕시   2250   2490   2577   2465   2542
17   하남시   2547   2687   2646   2671   2651
18   용인시   3373   3014   2901   3145   3302
19   파주시   4871   4753   4587   4603   5080
20   이천시   8594  11577  10090  11490  12993
21   안성시   4901   5151   5165   5309   5471
22   김포시   3269   3281   3266   3172   3235
23   화성시  10266  10766   9506   9839  10484
24   광주시   2808   2739   2670   2689   2829
25   양주시   3024   3109   3103   3048   3294
26   포천시   4370   4465   4645   4927   5102
27   여주시   3205   3497   3731   3867   4186
28   연천군   2908   3432   3974   4101   4404
29   가평군   2741   2944   2929   2977   3215
30   양평군   1638   1721   1758   1797   2079

In [7]:
grdp.sort_values(by='2021년',ascending=)

    시군구명  2017년  2018년  2019년  2020년  2021년
2    의정부   1598   1678   1686   1625   1614
12  남양주시   1541   1641   1678   1805   1822
11   구리시   1793   1864   1805   1758   1871
7   동두천시   1973   1870   1946   1922   1939
30   양평군   1638   1721   1758   1797   2079
9    고양시   1953   2086   2077   2048   2114
4    부천시   2013   2082   2119   2191   2227
16   의왕시   2250   2490   2577   2465   2542
13   오산시   2578   2622   2578   2463   2636
17   하남시   2547   2687   2646   2671   2651
15   군포시   2583   2703   2747   2659   2721
5    광명시   2274   2485   2435   2615   2754
24   광주시   2808   2739   2670   2689   2829
0    수원시   2854   2971   3080   2796   3031
29   가평군   2741   2944   2929   2977   3215
22   김포시   3269   3281   3266   3172   3235
25   양주시   3024   3109   3103   3048   3294
18   용인시   3373   3014   2901   3145   3302
3    안양시   2941   3144   3345   3221   3388
14   시흥시   3912   3766   3540   3465   3537
8    안산시   3898   3941   3969   3799   3964
27   여주시   3205   3497   3731   3867   4186
28   연천군   2908   3432   3974   4101   4404
19   파주시   4871   4753   4587   4603   5080
26   포천시   4370   4465   4645   4927   5102
1    성남시   4271   4455   4704   5030   5432
21   안성시   4901   5151   5165   5309   5471
6    평택시   6573   7010   6433   6091   6424
10   과천시   7871   8409   8340   7243   6885
23   화성시  10266  10766   9506   9839  10484
20   이천시   8594  11577  10090  11490  12993